---
version: '3'
services:
  # app:
  # build: .
  # links:
  #   - postgres
  # environment:
  #   - POSTGRES_URL="postgres://postgres:postgres@localhost:5432/booklist"
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres
    ports:
      - '5432:5432'
